# Generated by Django 4.2.7 on 2026-02-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_name', models.CharField(max_length=500, verbose_name='Nome Aprovado')),
                ('entrez_gene_id', models.BigIntegerField(unique=True, verbose_name='Entrez Gene ID')),
                ('mim_number', models.IntegerField(blank=True, null=True, verbose_name='MIM Number')),
                ('symbol', models.CharField(max_length=100, verbose_name='Símbolo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
                'db_table': 'genes',
                'ordering': ['entrez_gene_id'],
            },
        ),
    ]
